## 数据源  配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: yuanyuan121


## 端口号 配置
server:
  port: 8089

## Mybatis 配置
mybatis:
  type-aliases-package: org.spring.springboot.springboot_mybatis.entity
  mapper-locations: classpath:mapper/*.xml